# Generated by Django 4.0.3 on 2022-03-08 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=12)),
                ('IsActive', models.BooleanField(default=False)),
                ('DateCreated', models.DateTimeField(auto_now=True)),
                ('LastLogin', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=50)),
                ('Mobile', models.CharField(default='', max_length=10)),
                ('Gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=6)),
                ('City', models.CharField(default='', max_length=50)),
                ('State', models.CharField(default='', max_length=50)),
                ('Adderss', models.TextField(default='', max_length=150)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.master')),
            ],
        ),
    ]
