# Generated by Django 4.0.3 on 2022-03-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='master',
            table='master',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
