# Generated by Django 4.0.3 on 2022-03-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0005_category_quesset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='quesset',
            name='Question',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
