# Generated by Django 4.0.3 on 2022-03-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0007_remove_master_lastlogin_master_lastupdated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesset',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quesset',
            name='LastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
