# Generated by Django 4.0.3 on 2022-03-26 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0009_remove_quesset_correct_remove_quesset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesset',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.profile'),
            preserve_default=False,
        ),
    ]
